---

name: Push (main)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
    - main

jobs:
  create_npm_release:
    name: Create NPM Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: |
        npm install --global yarn
        yarn bootstrap-frozen
        yarn build
        chmod +x .github/scripts/write-npmrc.sh
        .github/scripts/write-npmrc.sh
        lerna publish from-package --no-verify-access --yes
