---

name: Push (main)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  create_npm_release:
    name: Create NPM Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: |
        rm -rf node_modules
        npm install --global yarn
        yarn install --frozen-lockfile
        yarn build
        lerna bootstrap --use-workspaces
        echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        lerna publish from-package --no-verify-access --yes

